# Generated by Django 4.2.7 on 2023-12-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Место проведения мероприятия',
                'verbose_name_plural': 'Места проведения мероприятий',
            },
        ),
        migrations.RemoveField(
            model_name='booking',
            name='cnt_section',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='cnts',
        ),
        migrations.AddField(
            model_name='booking',
            name='locations',
            field=models.ManyToManyField(to='main.eventlocation', verbose_name='Помещение'),
        ),
        migrations.AddField(
            model_name='room',
            name='locations',
            field=models.ManyToManyField(to='main.eventlocation'),
        ),
    ]
