# Generated by Django 4.2.7 on 2023-12-02 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='locations',
            field=models.ManyToManyField(related_name='room', to='main.eventlocation', verbose_name='Части помещения'),
        ),
    ]
