# Generated by Django 4.2.7 on 2023-12-07 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_name_event_type_eventtype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.IntegerField(choices=[(1, 'раз в неделю'), (2, 'раза в неделю'), (3, 'раза в неделю')])),
            ],
            options={
                'verbose_name': 'Вариант расписания',
                'verbose_name_plural': 'Варианты расписания',
            },
        ),
        migrations.CreateModel(
            name='ClubType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Вид кружка')),
            ],
            options={
                'verbose_name': 'Вид кружка',
                'verbose_name_plural': 'Виды кружков',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=60, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=60, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=60, verbose_name='Отчество')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
            },
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
            },
        ),
        migrations.CreateModel(
            name='ClubSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='Время начала занятий')),
                ('time_end', models.TimeField(verbose_name='Время окончания занятий')),
                ('weekday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.weekday', verbose_name='День недели')),
            ],
            options={
                'verbose_name': 'Расписание кружка',
                'verbose_name_plural': 'Расписание кружков',
            },
        ),
        migrations.CreateModel(
            name='ClubRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кружка')),
                ('datetime', models.DateTimeField(verbose_name='Дата начала работы кружка')),
                ('locations', models.ManyToManyField(related_name='club_registration', to='main.eventlocation', verbose_name='Помещение')),
                ('schedule', models.ManyToManyField(to='main.clubschedule', verbose_name='Расписание')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clubscheduletype', verbose_name='Вариант расписания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.teacher', verbose_name='Преподаватель')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clubtype', verbose_name='Тип кружка')),
            ],
            options={
                'verbose_name': 'Регистрация клуба',
                'verbose_name_plural': 'Регистрации клуба',
            },
        ),
    ]
