# Generated by Django 4.2.7 on 2023-12-07 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_populate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubregistration',
            name='schedule_type',
            field=models.IntegerField(choices=[(1, 'раз в неделю'), (2, 'раза в неделю'), (3, 'раза в неделю')], verbose_name='Вариант расписания'),
        ),
        migrations.AlterField(
            model_name='clubregistration',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clubtype', verbose_name='Вид кружка'),
        ),
        migrations.DeleteModel(
            name='ClubScheduleType',
        ),
    ]
