# Generated by Django 4.2.7 on 2023-12-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_clubregistration_schedule_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubregistration',
            options={'verbose_name': 'Регистрация кружка', 'verbose_name_plural': 'Регистрации кружков'},
        ),
        migrations.AlterField(
            model_name='clubregistration',
            name='schedule',
            field=models.ManyToManyField(related_name='club_registration', to='main.clubschedule', verbose_name='Расписание'),
        ),
        migrations.AlterField(
            model_name='clubregistration',
            name='schedule_type',
            field=models.IntegerField(choices=[(1, '1 раз в неделю'), (2, '2 раза в неделю'), (3, '3 раза в неделю')], verbose_name='Вариант расписания'),
        ),
    ]
