# Generated by Django 4.2.7 on 2023-12-09 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_event_date_alter_event_time_and_more'),
        ('main', '0014_populate'),
    ]

    operations = [
    ]
